### ISSUE TITLE
React Native 0.60.0+ support

### ISSUE THREAD

**Issue by tautvilas** [csath/react-native-config-reader#12]
npm link is depreciated in new React Native versions, but auto-linking does not work with this library. After lib reference is added to podfile, pod install does not work.

Probably #10  fixes this

**Comment by tautvilas** [comment]
Another related issue is that auto-linking fails on Android too, because package is contructed without BuildConfig.class parameter. I found a workaround for now to exclude this package from android auto linking via react-native.config.js

**Comment by csath** [comment]
Android Auto linking will be fixed by #17

**Comment by csath** [comment]
Closing down this issue since it is resolved with new version 4.0.1
