### ISSUE TITLE
Request to add an ability to write variables to support multi-tenant architecture

### ISSUE THREAD

**Issue by rodgomesc** [csath/react-native-config-reader#19]
first congrats for this amazing project, i would like to suggest, don't just read, but write variables too, if we could easily modify variables and native codes on android and ios, building a react native app for multi tenant architecture would be much more simple

**Comment by csath** [comment]
Thank you very much @rodgomesc for the suggestions. :) 
I'll look into this.

**Comment by prometheas** [comment]
Hey @rodgomesc - the author has just very kindly added me as a maintainer, and I'm taking a moment to review existing issues and PRs. I'm not sure I understand the value proposition on this one, however, as files like `Info.plist` are not meant to be immutable for any given app build — and good reason (security).

That said, I may be misunderstanding the nature of your feature request, so — if this is still relevant to you — may I trouble you to please unpack this further?

As I presently understand your request, however, I propose that you might consider creating a separate "layer" of local-storage-based configs, which uses values read by this package as its _default_ values to initialize the local storage values. The main complication I can foresee in that scenario is how to keep these values in sync as they may evolve over time, with app releases.

**Comment by prometheas** [comment]
Also, @rodgomesc, please note that I just re-titled the issue to be a bit more descriptive. Please let me know if my new title fails to capture or misrepresents your request.

**Comment by rodgomesc** [comment]
It's been a long time and now looking at it I don't know what I meant that day, I think it was the time I still drank while programming

**Comment by prometheas** [comment]
Ha! Thanks for confirming 🙂
