### ISSUE TITLE
Android - TypeError null is not an object...

### ISSUE THREAD

**Issue by cristianoccazinsp** [csath/react-native-config-reader#26]
Hello,

When reading variables on Android I'm getting `TypeError: null is not an object (evaluating '_reactNativeConfigReader.default.somevariable')`

**Comment by cristianoccazinsp** [comment]
Update: Was using a different `applicationId` for debug (multiple flavors), so I had to add:

`resValue "string", "rn_config_reader_custom_package", "my.package.app"` (without the custom id)

**Comment by abdulghanitech** [comment]
Facing the same issue!

**Comment by LeunensMichiel** [comment]
> Update: Was using a different `applicationId` for debug (multiple flavors), so I had to add:
> 
> `resValue "string", "rn_config_reader_custom_package", "my.package.app"` (without the custom id)

Yes! After a few hours of searching I found your solution. We had different flavors (for whitelabel apps) as well. Your solution was applicable for my use case as well, thanks!
