### ISSUE TITLE
NPM 7 : Update React-Native Version from 0.41.2

### ISSUE THREAD

**Issue by johnny-minty** [csath/react-native-config-reader#30]
In version **4.1.1** the react-native version referenced is '^0.41.2"' which is very old.  This is now an issue with NPM 7 as peer dependencies are taken into account and the build will fail without using the '-legacy-peer-deps' or the '--force' flags.

**NPM Release Article:** 
https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

**Systems Affected:** 
Anyone running NPM 7 with a recent version of React-native

**Comment by cristianoccazinsp** [comment]
Looking for this as well, is this library even still maintained? @csath

**Comment by prometheas** [comment]
Hey, @csath - any chance you can knock this one out? 😄 🙏 ❤️

**Comment by prometheas** [comment]
As a heads up to the folks who've commented on this issue, I've created PR #39 which should fix it. I've also directly emailed the author (in case they aren't actively monitoring GitHub alerts), offering to assist with maintenance.

I'm hoping to avoid creating yet another unofficial fork of a project on NPM, but volunteer-maintained OSS is obviously a complex landscape.

Anyway, let's see how this plays out 🤞

**Comment by prometheas** [comment]
Hey @johnny-minty and @cristianoccazinsp - hope this doesn't feel to "spammy", but I posted a pseudo-issue (#41) about exploring a community fork, in case you'd be interested.

**Comment by prometheas** [comment]
Hey, @johnny-minty and @cristianoccazinsp - as I've noted on #41, the author has added me as a maintainer for the project and I was finally able to merge my own PR that addressed the peer dependencies.

Per my note on the closing comment of #41, however, I remain unable to publish to NPM. But you'll be able to [resolve this dependency via GitHub](https://docs.npmjs.com/cli/v8/commands/npm-install) until such time as I can work with the author to get NPM publishing in place.

**Comment by cristianoccazinsp** [comment]
@prometheas awesome, thanks for taking care of it. Hopefully there's an easy way in the future for you to also release to NPM. Luckily, the package does not need any transpile/compile step from TSC, so it can be used right away from the package.json file.
